name: Daily cronjobs
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  daily-cronjobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Get latest financial statement releases from IDX
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/idx_latest_release_date.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stocks_list
          path: stocks_list.txt
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: stocks_list
          path: artifact
      - name: Scrape financial data from Stockbit
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          STOCKS_LIST=$(cat artifact/stocks_list.txt)
          python src/stock_analysis/stockbit/stockbit_data_scraper.py $STOCKS_LIST
      - name: Send daily email for latest financial statement releases
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GMAIL_ID: ${{ secrets.GMAIL_ID }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python src/stock_analysis/send_email_notification.py
