name: Send daily email for the latest financial statement releases from IDX
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  get-release-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Get latest financial statement releases from IDX
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/idx_latest_release_date.py
  send-email:
    needs: get-release-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Create daily email financial statement releases from IDX
        env:
          GMAIL_ID: ${{ secrets.GMAIL_ID }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python src/stock_analysis/send_email_notification.py
