name: Get latest financial statement releases from IDX
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Create daily to get latest financial statement releases from IDX
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/idx_latest_release_date.py
