name: Cronjob to scrape data from Trading View webiste
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Scrape fundamental data from Trading View website
      run: |
        python src/tradingview_scraper/fundamental_data_scraper.py
