name: Scrape Stockbit Statement Release Date
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Stockbit website 1
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          python src/stock_analysis/stockbit/stockbit_statement_release_date_scraper.py
