name: Scrape TradingView Financials
on:
  schedule:
    - cron: "0 8 * * 1"
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Trading View website
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python src/stock_analysis/tradingview_data_scraper.py
