name: Scrape Stockbit Financials
on:
  schedule:
    - cron: "0 8 * * 1"
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  job7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Stockbit website 7
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/stockbit/stockbit_data_scraper_7.py
