name: Scrape Stockbit Financials
on:
  schedule:
    - cron: "0 8 * * 1"
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Stockbit website 1
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/stockbit/stockbit_data_scraper_1.py
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Stockbit website 2
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/stockbit/stockbit_data_scraper_2.py
  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Stockbit website 3
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/stockbit/stockbit_data_scraper_3.py
  job4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Stockbit website 4
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/stockbit/stockbit_data_scraper_4.py
  job5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Scrape fundamental data from Stockbit website 5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          STOCKBIT_USERNAME: ${{ secrets.STOCKBIT_USERNAME }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
        run: |
          python src/stock_analysis/stockbit/stockbit_data_scraper_5.py
