name: Send Email Notification for IDX Financial Statement Releases
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Create daily notification via email for IDX financial statement releases
        env:
          GMAIL_ID: ${{ secrets.GMAIL_ID }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python src/stock_analysis/send_email_notification.py
